

GET http://localhost:3000/api/customers

###

GET http://localhost:3000/api/customers/6336bc6b9ada6332dda44930

###

// destination IS found inside current route.
GET http://localhost:3000/api/seekRoute/Köping+Arboga

###

// destination is not found inside current route.
GET http://localhost:3000/api/seekRoute/Köping+Hyllie

###

GET http://localhost:3000/api/getUniqueStations

###














POST http://localhost:3000/api/tickets
Content-Type: application/json

{
    "bookingId": "633be8ed3d9297b45976df56",
    "trainNumber":"6336ca454ee5294617aea153",
    "route": "6336d0e24ee5294617aea162",
    "departureTime": "2022-10-24",
    "departureStation": "633ac6b165b9cde5dd6cb181",
    "arrivalStation": "633ac75b65b9cde5dd6cb193",
    "ticketPrice": "420"
    
}

###

DELETE http://localhost:3000/api/customers/