GET http://localhost:3000/api/customers

###

POST http://localhost:3000/api/customers
Content-Type: application/json

{
    "customerName": "Gunde Svan",
    "email": "gundeman@gmail.com",
    "telephoneNumber": "0764651321"
}