
GET http://localhost:3000/api/customers

###

POST http://localhost:3000/api/customers
Content-Type: application/json

{
    "customerName": "Gunde2 Svan",
    "email": "gundeman@gmail.com",
    "telephoneNumber": "0764651321"
}

###

POST http://localhost:3000/api/customers
Content-Type: application/json

{
    
    "customerName": "Gunde2 Svan",
    "email": "gundeman@gmail.com",
    "telephoneNumber": "0764651321"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "passWord": "hejsan123",
    "userID": "6335e21b4de4c07fb59b591c"
}